# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3], [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3], [4,5,6]], [[4,5,6], [7,8,9]], [[10,11,12],[13,14,15]]])

a1, a2, a3

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15]]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.ndim, a1.dtype, a1.size, type(a1)

(1, dtype('int64'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.ndim, a2.dtype, a2.size, type(a2)

(2, dtype('int64'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.ndim, a3.dtype, a3.size, type(a3)

(3, dtype('int64'), 18, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

a1_df = pd.DataFrame(a1)
a1_df

0
0  1
1  2
2  3

In [7]:
# Create an array of shape (10, 2) with only ones
ones = np.ones(shape=(10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros(shape=(7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
a4 = np.arange(0, 100 ,3)
a4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a5 = np.random.randint(10, size=(7, 2))
a5

array([[4, 3],
       [2, 2],
       [5, 0],
       [1, 2],
       [4, 8],
       [2, 1],
       [9, 5]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a6 = np.random.rand(3,5)
a6

array([[0.22371378, 0.67475634, 0.1336138 , 0.11753362, 0.43260712],
       [0.96869692, 0.25271391, 0.23051457, 0.86048494, 0.68108262],
       [0.44969575, 0.53052556, 0.10627774, 0.2578965 , 0.62628321]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
a7 = np.random.randint(10, size=(4,6))
a7

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

a8 = np.random.randint(10, size=(3, 7))

# Find the unique numbers in the array you just created
a8, np.unique(a8)

(array([[8, 0, 9, 2, 6, 3, 8],
        [2, 4, 2, 6, 4, 8, 6],
        [1, 3, 8, 1, 9, 8, 9]]),
 array([0, 1, 2, 3, 4, 6, 8, 9]))

In [14]:
# Find the 0'th index of the latest array you created
a8
a8[0]

array([8, 0, 9, 2, 6, 3, 8])

In [15]:
# Get the first 2 rows of latest array you created
a8[:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [16]:
a8

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6],
       [1, 3, 8, 1, 9, 8, 9]])

In [17]:
# Get the first 2 values of the first 2 rows of the latest array
a8[:2,:2]

array([[8, 0],
       [2, 4]])

In [18]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

a9 = np.random.randint(10, size=(3,5))
a9_ones = np.ones(shape=(3,5), dtype=int)

In [19]:
a9

array([[4, 1, 3, 6, 7],
       [2, 0, 3, 1, 7],
       [3, 1, 5, 5, 9]])

In [20]:
a9_ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
# Add the two arrays together
a9 + a9_ones

array([[ 5,  2,  4,  7,  8],
       [ 3,  1,  4,  2,  8],
       [ 4,  2,  6,  6, 10]])

In [22]:
# Create another array of ones of shape (5, 3)
a10 = np.ones(shape=(5, 3), dtype=int)
a10

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [23]:
# Try add the array of ones and the other most recent array together
# a9 + a10

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

- by reshaping

In [24]:
# Create another array of ones of shape (3, 5)

a11 = np.ones(shape=(3,5), dtype=int)
a11

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
# Subtract the new array of ones from the other most recent array
a10.shape, a11.shape

((5, 3), (3, 5))

In [26]:
a9 - a11

array([[ 3,  0,  2,  5,  6],
       [ 1, -1,  2,  0,  6],
       [ 2,  0,  4,  4,  8]])

In [27]:
# Multiply the ones array with the latest array
a11 * a9

array([[4, 1, 3, 6, 7],
       [2, 0, 3, 1, 7],
       [3, 1, 5, 5, 9]])

In [28]:
# Take the latest array to the power of 2 using '**'
a9 ** 2

array([[16,  1,  9, 36, 49],
       [ 4,  0,  9,  1, 49],
       [ 9,  1, 25, 25, 81]])

In [29]:
# Do the same thing with np.square()
np.square(a9)

array([[16,  1,  9, 36, 49],
       [ 4,  0,  9,  1, 49],
       [ 9,  1, 25, 25, 81]])

In [30]:
# Find the mean of the latest array using np.mean()
np.mean(a9)

3.8

In [31]:
# Find the maximum of the latest array using np.max()
np.max(a9)

9

In [32]:
# Find the minimum of the latest array using np.min()
np.min(a9)

0

In [33]:
# Find the standard deviation of the latest array
a9.std()

2.5612496949731396

In [34]:
# Find the variance of the latest array
a9.var()

6.5600000000000005

In [35]:
# Reshape the latest array to (3, 5, 1)
a9.reshape(3,5,1)

array([[[4],
        [1],
        [3],
        [6],
        [7]],

       [[2],
        [0],
        [3],
        [1],
        [7]],

       [[3],
        [1],
        [5],
        [5],
        [9]]])

In [36]:
# Transpose the latest array
a9.T

array([[4, 2, 3],
       [1, 0, 1],
       [3, 3, 5],
       [6, 1, 5],
       [7, 7, 9]])

What does the transpose do?

    - interchange the rows with columns

In [37]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)

a12 = np.random.randint(10, size=(3,3))
a13 = np.random.randint(10, size=(3,2))

In [38]:
a12, a13

(array([[3, 5, 1],
        [9, 1, 9],
        [3, 7, 6]]),
 array([[8, 7],
        [4, 1],
        [4, 7]]))

In [39]:
# Perform a dot product on the two newest arrays you created
np.dot(a12, a13)

array([[ 48,  33],
       [112, 127],
       [ 76,  70]])

In [40]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)

a14 = np.random.randint(10, size=(4,3))
a14

array([[9, 8, 8],
       [0, 8, 6],
       [8, 7, 0],
       [7, 7, 2]])

In [41]:
# Perform a dot product on the two newest arrays you created

np.dot(a13.T, a14.T)

array([[136,  56,  92,  92],
       [127,  50,  63,  70]])

It doesn't work. How would you fix it?

 - by transposing them

In [42]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [43]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables

a15 = np.random.randint(10, size=(2,3))
a16 = np.random.randint(10, size=(2,3))

a15, a16

(array([[0, 7, 2],
        [2, 0, 4]]),
 array([[9, 6, 9],
        [8, 6, 8]]))

In [44]:
# Compare the two arrays with '>'
a15 > a16

array([[False,  True, False],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [45]:
# Compare the two arrays with '>='

a15 >= a16

array([[False,  True, False],
       [False, False, False]])

In [46]:
# Find which elements of the first array are greater than 7

a15 > 7

array([[False, False, False],
       [False, False, False]])

In [47]:
# Which parts of each array are equal? (try using '==')

a15 == a16

array([[False, False, False],
       [False, False, False]])

In [48]:
# Sort one of the arrays you just created in ascending order

a15.sort()
a15

array([[0, 2, 7],
       [0, 2, 4]])

In [49]:
# Sort the indexes of one of the arrays you just created

a16.argsort()

array([[1, 0, 2],
       [1, 0, 2]])

In [50]:
# Find the index with the maximum value in one of the arrays you've created

a16.argmax()

0

In [51]:
# Find the index with the minimum value in one of the arrays you've created
a6.argmin(), a6

(12,
 array([[0.22371378, 0.67475634, 0.1336138 , 0.11753362, 0.43260712],
        [0.96869692, 0.25271391, 0.23051457, 0.86048494, 0.68108262],
        [0.44969575, 0.53052556, 0.10627774, 0.2578965 , 0.62628321]]))

In [52]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created

a6.argmax(axis=1)

array([1, 0, 4])

In [53]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created

a6.argmin(axis=0)

array([0, 1, 2, 0, 0])

In [54]:
# Create an array of normally distributed random numbers

a17 = np.random.normal(size=(1, 4))
a17

array([[-1.50815329,  1.09964698, -0.17773212, -0.41038331]])

In [55]:
# Create an array with 10 evenly spaced numbers between 1 and 100

a18 = np.linspace(1, 100, 10)
a18

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.